### ISSUE TITLE
Add support for phonetic-feature matching

### ISSUE THREAD

**Issue by samanthamccabe** [samanthamccabe/toolbox-sca#2]
* Support loading of a feature model from the script
* Support use of feature labels in rule transform
* Support use of feature labels in state machines

**Comment by sfmorrigan** [comment]
Create tests in RuleTest with transform and context using features, and work back from there based on emerging needs.

**Comment by samanthamccabe** [comment]
This work has been done. We identified a bug in how state machines handled some of the functionality, but at the level of Segments, the code appears to work correctly. And additional problems will warrant additional bug tickets.
